version: 2.1
orbs: 
  aws-ecr: circleci/aws-ecr@7.3.0

workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build-and-push-image:
          create-repo: true
          dockerfile: Dockerfile
          path: .
          repo: ecrdockerrightbell
          tag: 'latest'
          type: approval