version: 2.1
orbs: 
  aws-ecr: circleci/aws-ecr@7.3.0
  aws-ecs: circleci/aws-ecs@2.2.1

workflows:
  build_and_push_image:
    jobs:
      - approvefirst:
          type: approval  
      - aws-ecr/build-and-push-image:
          # filters:
          #   branches:
          #     only:
          #       - main
          dockerfile: Dockerfile
          path: .
          repo: ecrdockerrightbell 
          tag: 'latest'
          requires: 
            - approvefirst
      - aws-ecs/deploy-service-update:
          cluster-name: 't2Docker-cluster'
          container-image-name-updates: 'container=t2Docker-service,tag=latest'
          family: 'TaskRIghtBell-service'
          requires:
            - aws-ecr/build-and-push-image  
      # - aws-ecr/build-and-push-image:
      #     filters:
      #       branches:
      #         only:
      #           - develop
      #     dockerfile: Dockerfile.dev
      #     path: .
      #     repo: ecrdevrightbell
      #     tag: 'latest'
          