version: 2.1
orbs: 
  aws-ecr: circleci/aws-ecr@7.3.0

workflows:
  build_and_push_image:
    jobs:
      - approvefirst:
          type: approval  
      - aws-ecr/build-and-push-image:
          # filters:
          #   branches:
          #     only:
          #       - main
          dockerfile: Dockerfile
          path: .
          repo: ecrdockerrightbell 
          tag: 'latest'
          requires: 
            - approvefirst
      # - aws-ecr/build-and-push-image:
      #     filters:
      #       branches:
      #         only:
      #           - develop
      #     dockerfile: Dockerfile.dev
      #     path: .
      #     repo: ecrdevrightbell
      #     tag: 'latest'
          